export const cars = [
  {
    id: 1,
    name: "Koenigsegg",
    type: "Sport",
    capacity: 2,
    transmission: "Manual",
    fuel: "90L",
    price: 99,
    oldPrice: null,
    favorite: true,
    image: "Koenigsegg"
  },
  {
    id: 2,
    name: "Nissan GT-R",
    type: "Sport",
    capacity: 2,
    transmission: "Manual",
    fuel: "80L",
    price: 80,
    oldPrice: 100,
    favorite: false,
    image: "Nissan GT-R"
  },
  {
    id: 3,
    name: "Rolls-Royce",
    type: "Sedan",
    capacity: 4,
    transmission: "Manual",
    fuel: "70L",
    price: 96,
    oldPrice: null,
    favorite: true,
    image: "Rolls-Royce"
  },
  {
    id: 4,
    name: "Nissan GT-R",
    type: "Sport",
    capacity: 2,
    transmission: "Manual",
    fuel: "80L",
    price: 80,
    oldPrice: 100,
    favorite: false,
    image: "Nissan GT-R"
  },
  {
    id: 5,
    name: "All New Rush",
    type: "SUV",
    capacity: 6,
    transmission: "Manual",
    fuel: "70L",
    price: 72,
    oldPrice: 80,
    favorite: false,
    image: "All New Rush"
  },
  {
    id: 6,
    name: "CR-V",
    type: "SUV",
    capacity: 6,
    transmission: "Manual",
    fuel: "80L",
    price: 80,
    oldPrice: null,
    favorite: true,
    image: "CR-V"
  },
  {
    id: 7,
    name: "All New Terios",
    type: "SUV",
    capacity: 6,
    transmission: "Manual",
    fuel: "90L",
    price: 74,
    oldPrice: null,
    favorite: false,
    image: "All New Terios"
  },
  {
    id: 8,
    name: "CR-V",
    type: "SUV",
    capacity: 6,
    transmission: "Manual",
    fuel: "80L",
    price: 80,
    oldPrice: null,
    favorite: true,
    image: "CR-V"
  },
  {
    id: 9,
    name: "MG ZX Exclusive",
    type: "Hatchback",
    capacity: 4,
    transmission: "Manual",
    fuel: "70L",
    price: 76,
    oldPrice: 80,
    favorite: true,
    image: "MG ZX Exclusive"
  },
  {
    id: 10,
    name: "New MGZS",
    type: "SUV",
    capacity: 6,
    transmission: "Manual",
    fuel: "80L",
    price: 80,
    oldPrice: null,
    favorite: false,
    image: "New MGZS"
  },
  {
    id: 11,
    name: "MG ZX Excite",
    type: "Hatchback",
    capacity: 4,
    transmission: "Manual",
    fuel: "90L",
    price: 74,
    oldPrice: null,
    favorite: true,
    image: "MG ZX Excite"
  },
  {
    id: 12,
    name: "New MGZS",
    type: "SUV",
    capacity: 6,
    transmission: "Manual",
    fuel: "80L",
    price: 80,
    oldPrice: null,
    favorite: false,
    image: "New MGZS"
  }
]